### ISSUE TITLE
Paragraph end quotes skipping past headings

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/md2gemini#10]

**Comment by makeworld-the-better-one** [comment]
TODO: Create a test case

**Comment by makeworld-the-better-one** [comment]
Links inside lists might be playing a role in causing this.

**Comment by karlb** [comment]
Here's a test case that fails for me:

```
# Headline

text

* [foo](foo.md)
* [bar](bar.md)

## Sub head

more text
```

results in

```
# Headline

text

* foo[1]
* bar[2]

## Sub head

more text

=> foo.md 1: foo.md
=> bar.md 2: bar.md
```

but should be

```
# Headline

text

* foo[1]
* bar[2]

=> foo.md 1: foo.md
=> bar.md 2: bar.md

## Sub head

more text
```

**Comment by karlb** [comment]
This also has the unpleasant side effect that on a page that only contains lists and headlines, the links are not added at all.

**Comment by makeworld-the-better-one** [comment]
Yikes, I'll look into this. Thanks for the test case and info. If anyone else wants to look into the code that'd be appreciated as well, as I don't necessarily have a lot of time to devote to this right now.
