### ISSUE TITLE
Html Stripping - keep inner text

### ISSUE THREAD

**Issue by krixano** [makeworld-the-better-one/md2gemini#12]
Currently, it looks like when you strip html, you strip all of it's contents, including the text. It'd be cool to keep the text contents, if it's not too much trouble.

**Comment by makeworld-the-better-one** [comment]
I think that would require a whole other library, and would cause lots of unwanted behaviour, as in text you didn't expect would be displayed would appear. Could you give an example usecase?

**Comment by krixano** [comment]
For example
```
<strong>Please support my project at the patreon here</strong>
```

I would like to keep `Please support my project at patreon here`, but just get rid of the html tags. This shouldn't be too hard I don't think if you're already parsing html tags, just remove the opening and closing and leave the inner text.

**Comment by makeworld-the-better-one** [comment]
Hmm, that should be the default behaviour, I tested for it. I just tested now again and it worked as it should, see the `test.py` and `test.md` files in the repo. Can you provide an example file that fails?

```
❯ echo '<strong>Please support my project at the patreon here</strong>' | md2gemini --strip-html
Please support my project at the patreon here
```

**Comment by krixano** [comment]
Ok, will do in a few minutes. Thanks.

**Comment by makeworld-the-better-one** [comment]
Can this be closed?

**Comment by krixano** [comment]
Hold on... I still need to check on this. Sorry, I've been busy with other things.

**Comment by makeworld-the-better-one** [comment]
No worries, I'll keep it open.

**Comment by makeworld-the-better-one** [comment]
@krixano Have you been able to reproduce this? No worries either way.
