### ISSUE TITLE
Transform local links with no extension to links with .gmi extension

### ISSUE THREAD

**Issue by raspbeguy** [makeworld-the-better-one/md2gemini#26]
Hello,

This library is very useful, thanks for all the work.

I am aware af the `md_links` parameter about transforming local links with the `.md` extension to the `.gmi` extension. However, some dynamic markdown-based CMS like PicoCMS hide the `.md` extension in URLs for aesthetic purpose, so local links in source mardown files do not contain the `.md` extention.

Wouldn't it be interresting to extend the local `.md`-to-`.gmi` link replacement to cover that use case?

Thanks.

EDIT: Maybe even better: an option to apply a custom function to any local links.

**Comment by makeworld-the-better-one** [comment]
Hello, glad this library is useful to you!

> EDIT: Maybe even better: an option to apply a custom function to any local links.

I might be more in favour of this actually, instead of adding more custom options. But it would have to be something that was used by calling md2gemini in Python, not from the command line. Does that still work for you?

**Comment by raspbeguy** [comment]
> But it would have to be something that was used by calling md2gemini in Python, not from the command line. Does that still work for you?

Works for me :+1:

**Comment by raspbeguy** [comment]
I created #27 to fix this issue.
