### ISSUE TITLE
Issue with the missing `link_func`

### ISSUE THREAD

**Issue by brunobord** [makeworld-the-better-one/md2gemini#28]
I've tried to convert Markdown documents (including this project README.md file) using `md2gemini` and I've failed each time with the following error:

```sh
md2gemini README.md
Traceback (most recent call last):
  File "/home/novapost/.virtualenvs/EXP37/bin/md2gemini", line 11, in <module>
    load_entry_point('md2gemini', 'console_scripts', 'md2gemini')()
  File "/home/novapost/Projets/Various/Gemini/md2gemini/md2gemini/__init__.py", line 351, in main
    __convert_file(file, args)
  File "/home/novapost/Projets/Various/Gemini/md2gemini/md2gemini/__init__.py", line 215, in __convert_file
    link_func=args.link_func,
AttributeError: 'Namespace' object has no attribute 'link_func'
```

I've also tried using the ``--links`` option, and same as above, it fails, with any of the possible values:

```
$ md2gemini --links=off README.md 
Traceback (most recent call last):
  File "/home/novapost/.virtualenvs/EXP37/bin/md2gemini", line 11, in <module>
    load_entry_point('md2gemini', 'console_scripts', 'md2gemini')()
  File "/home/novapost/Projets/Various/Gemini/md2gemini/md2gemini/__init__.py", line 351, in main
    __convert_file(file, args)
  File "/home/novapost/Projets/Various/Gemini/md2gemini/md2gemini/__init__.py", line 215, in __convert_file
    link_func=args.link_func,
AttributeError: 'Namespace' object has no attribute 'link_func'
```

I've grepped the code a little bit, and I was puzzled to see that the ``--links`` exists, as in https://github.com/makeworld-the-better-one/md2gemini/blob/master/md2gemini/__init__.py#L284-L289 ; but this arg is never mapped into a ``link_func``.

This regression occurs after installing v1.8.0 **and** on the master branch.

I've tried the v1.7.0 and it worked successfully!
So I think that the regression comes from: https://github.com/makeworld-the-better-one/md2gemini/compare/v1.7.0...v1.8.0

**Comment by makeworld-the-better-one** [comment]
Yes, the link func is something different than `--links`. See #26 and #27. I've fixed this bug, and will release v1.8.1 for you to use instead. Thanks for bringing this to my attention! There are tests that run for each commit, but all the tests are within Python, not for CLI usage, so I didn't notice this.

**Comment by makeworld-the-better-one** [comment]
Release made, v1.8.1 is on PyPI.

**Comment by brunobord** [comment]
tested and validated!
thank you for this quick patch!

**Comment by makeworld-the-better-one** [comment]
You're welcome! Enjoy md2gemini.
