### ISSUE TITLE
Links in lists

### ISSUE THREAD

**Issue by snan** [makeworld-the-better-one/md2gemini#30]
`<li><a href=foo>bar</a></li>`

becomes

`* bar`

I want it to become

`=> foo bar`

**Comment by makeworld-the-better-one** [comment]
Yeah, ignoring the link is probably the wrong move here. Although I wonder what to do about the list item. Should an asterisk be put in front? Or maybe a bullet: `•`

**Comment by snan** [comment]
I just turned

* [et](/cetera)

into

=> /cetera et

**Comment by makeworld-the-better-one** [comment]
Yes, but I am just wondering aloud if there is going to be a semantic difference between a link in a list versus just a link on its own line. For example, there might be regular list lines in between the ones with links, or sub-levels of the list. I will think about this more and then fix it.

**Comment by makeworld-the-better-one** [comment]
> I noticed that if a line finished with a link, it breaks, but works if you add a ";" or anything at the end of the line after the link

https://framapiaf.org/@bacardi55/105859804808145894

**Comment by snan** [comment]
OK.

[This is what I'm trying now.](gemini://idiomdrottning.org/gemini-links)

This is buiding on md2gemini's fantastic "copy" mode. The goal, of course, is "How would this document look if I had written it in Gemini in the first place?"

I kinda gave up on mistune but in hindsight I'm not sure that was the right idea; there was just as much work to do with the comparse-based lowdown.scm that I ended up using.

In Gemini documents, whether Lagrange or AV-98 or Elpher, I kinda don't mind seeing

    * non-link lines
    => /page and link lines
    => /home all mixed up
    * together

My feeling is that each link line is part of a dirlisting almost, and dirlistings can have some "inert"/"informative" lines. Akin to how Gophermaps do it.

**Comment by snan** [comment]
What I did up till now on my previous mistune/md2gemini based rig was that I did a lot of pre- and postprocessing. Changing `- [foo][bar]` into just `[foo][bar]` was part of a preprocessing step. Removing blank lines between list lines was a postprocessing step.
I did some other stuff to, to handle includes and such.

**Comment by makeworld-the-better-one** [comment]
Thanks for thinking about this and putting time into this issue!

> The goal, of course, is "How would this document look if I had written it in Gemini in the first place?"

100% that's the right goal.

```
* non-link lines
=> /page and link lines
=> /home all mixed up
* together
```

This looks ok to me, although I think breaking up the line is not building on the copy mode, and would get ugly for longer bullet points with several links. Why not emulate copy mode? Like this:

```markdown
- List line with [some link](https://example.com)
- Another line
```
becomes
```
* list line with some link
=> https://example.com some link
* Another line
```

> my previous mistune/md2gemini based rig

I would love to see this, or get some PRs based on the improvements you have. That way we can move toward closing this issue using the existing md2gemini system.

Thanks!

**Comment by snan** [comment]
Oh, I don't break up lines. If a list line has more than one line, I
don't split it. That example was meant as an example with the links
already on two separate links in the Markdown source.

So here's your example:

	- List line with [some link](https://example.com)
	- Another line

So what the existing copy mode would do in this situation is rather something like this:

	* list line with some link
	* Another line

    => https://example.com some link

What mine does is:

	=> https://example.com List line with some link
	* Another line

I have three kinds of links:

1. Reference links → the location of the reference is where the link is.
2. Explicit links in short p or li where there is only one link. "Short" means either the p/li is under 60 chars, or, the link label is more than half the text. → the entire p/li becomes the link.
3. Explicit links in longer p or li, or when there are more than one link in the p or li. → Like copy mode, except that in copy mode the link is inserted directly underneath the paragraph/list. Mine waits until the end of the entire section, or, just ahead of any other non-copy-moded link.

Since making this, I mostly use "reference" links. That way I can control exactly where the link lines will go.

Also, if there is a "link title", that's whats used for the gemini text.


	My superlong p with [a short link](/url "The Vaguaries of Urlery") and a
	long paragraph of lorem ipsum dolor sit a met and so on for ages and ages

Becomes

	My superlong p with a short link and a long paragraph of lorem ipsum dolor sit a met and so on for ages and ages

	=> /url The Vaguaries of Urlery


> I would love to see this, or get some PRs based on the improvements you have.

My old rig was just md2gemini but before running md2gemini, I ran the text through a scheme thing that handled file includes and also (completely textually, without doing any parsing) turned `- [foo][bar]` into`\n[foo][bar]\n` and then after running md2gemini ran another text filter to remove blank lines between link lines. I didn't do it properly, in the Python.

The limitations of this rig, that never got right, using it, was as I outlined above:

- it used link labels rather than link titles. This could often get weird, lower case names for links etc.
- it copied the links to just after the paragraph instead of where I'd often want them, at the end of the section or sometimes the end of the entire document

That's probably not impossible to fix in the Python. I just got an embarrassing and wrong case of Not Invented Here and thought I'd "whip up a better system in a night or two in a more comfortable language" and ended up spending a month on it and a desire to abandon my former fave language, Scheme.💔

I also fixed another long-standing bug, maybe this is something that more recent versions of md2gemini has already addressed but the oldish release of it that I had (python and venvs are difficult for my li'l tired head to work with) would not handle line wrapping in blockquotes well.

(I also replaced gemfeed, that was much more satisfying because that *did* only end up taking a few minutes and ended up with an overall faster and more reliable system—that's less a slag on gemfeed itself but on the absolutely ridic amounts of pre- and postprocessing I was doing on both on the gemfiles to create good gemfeed fodder, and on the gemfeed atom itself. That's a change I shoulda made a long time ago but that's completely off topic to the question of md2gemini.)

I went through kinda three phases with md2gemini.

First, the "I kinda don't care too much about the gemini version of the site, people can read there at their own risk and I'm actually pleasantly surprised at whatever md2gemini gives me with just -wfpsl copy" phase. This was good but sometimes what would happen is exactly as I've outlined here as sort of "shortcomings" of copy mode: weird textual repeats in lower case. Like if \[this paragraph had brackets\] we'd get

this paragraph has brackets

repeated, all lower case since it came from a mid-sentence context, in the output text.

Then, second, the "oops, I actually ended up really loving gemini, let me make sure the gemini version looks really good". This is when I went through a phase of writing markdown files that ended with a list of links, and I wrote the pre-/post-processing stuff for md2gemini to take advantage of that. That created some good-looking gemini files but it was at the expense of the web version, which no longer had real hyperlinks but instead got stuck with the same list-of-link style as was intended for gemini. (Some might thing of that isomorphism as a feature.)

Then the third phase after I had came up with the ideas for how I wanted it to work instead of copy mode, and I started writing pages "as if I already had the new thing working". So my web versions started looking good again, at the expense of the gem versions. (For all intents and purps, this phase is similar in practice to phase one in how the web pages and the gem pages worked.)

And then it took me longer than I hoped to actually get my new NIH thing in place but now I have it. So now all my stuff from phase one, phase two, and phase three look good on the gemini versions, and the only pages that look bad are the web versions from phase two and the gemini versions of pre-phase-one, i.e., the ones written before I had even heard of gemini or md2gemini. I'll gradually work on those as I find issues with them.

IDK I feel hesitant for even hitting send on this stuff. I feel guilty AF for writing my own stuff instead of pooling my efforts on md2gemini. (OTOH, everyone and their horse has their own server, it sometimes seems… but there are way fewer md2gemini things and I should've been pooling my efforts with you instead. I just got so frustrated with mistune, but, lowdown.scm ended up having its own limitations.)

**Comment by makeworld-the-better-one** [comment]
Don't feel guilty! I appreciate help on this project, but there's nothing wrong with doing your own thing.

If I can recap, I think I can say now that I'm aganst putting the link inside the list:

```
=> https://example.com List line with some link
* Another line
```

I think it will look weird on many clients, and this strategy breaks down when there are multiple links.

IMO the best method is to treat all the whole list as a paragraph, and then just apply whatever links mode is already in use. So copy mode would look like this as @snan said:

```
* list line with some link
* Another line

=> https://example.com some link
```

**Comment by snan** [comment]
I def do it the first way, treating => as <li><a>

Additionally, short enough paragraphs I make the entire paragraph the link now.

**Comment by makeworld-the-better-one** [comment]
Personally I just don't think that's the way to go, I find it looks strange on clients.

Lagrange:

![image](https://user-images.githubusercontent.com/25111343/145243300-8a3d28b5-9634-41c0-bd25-3ff62ff61da2.png)

Amfora:

![image](https://user-images.githubusercontent.com/25111343/145243440-c4b4fb75-9389-4bcc-8f24-e937fdf50a9b.png)

**Comment by makeworld-the-better-one** [comment]
> IMO the best method is to treat all the whole list as a paragraph, and then just apply whatever links mode is already in use. 

Turns out the code already does this! The bug as originally reported (link disappearing) no longer occurs. I fixed an issue with extra newlines being generated in 1bcd5e7, and so I'd say this issue can be closed.

@snan let me know if you find any further bugs with this, but I don't think I will be supporting transforming list items into links.

**Comment by snan** [comment]
Yeah. I really disagreed with Lagrange's decision to bold the link lines. The previous versions of Lagrange, when it was just an icon in the margin, looked so good.

I just think it looks really weird to have a list and then to have the same text just below it, as a link.

I've come up with a way to have more control over how links look though:

When translating HTML links to Gemini, you can use the "title"
attribute of the link as the link title.

In Markdown, that looks like this:

	Hi, here's my [thing that I just casually mention][tt] sometimes.

	[tt]: gemini://my.boring/url "I like this link"

becomes

	Hi, here's my thing that I just casually mention sometimes.

	=> gemini://my.boring/url I like this link

In Markdown, you can also use the reference location as the link
location.

**Comment by makeworld-the-better-one** [comment]
Ah ok, interesting. Is this something you'd like md2gemini to support as well?

**Comment by snan** [comment]
I don't currently use md2gemini (because of this) but I think it's a good idea.

When there is no title, I use the link text (the way md2gemini does it), and when there is no reference location, I have a bunch of weird, over-engineered heuristics for where the link should go (if it's the only link in a short li or p (regardless of how much of that li or p it is), or if it's more than a certain percent of the li or p (regardless of how long that li or p is), then the entire li or p becomes the link. Otherwise, it goes before the next header or at the end of the document.)

I wanted to support the

    => gemini://foo.bar/baz foo wrote:
    > a quote by foo

idiom.

It's great because that's

    [foo wrote](gemini://foo.bar/baz):
    > a quote by foo

in Markdown (note the colon character's position).

This is all super over-engineered and cumbersome, I know 💔 but I just wanted the gemini pages and the HTML pages to both look as if they were handcrafted, the only or primary version.

**Comment by makeworld-the-better-one** [comment]
Ah that example would be nice to support yeah. Tricky though, so I'm not sure if it will make its way here. I'll think about it, but it seems like an edge case, I can't really think of another example like that where the link being inserted below breaks the flow a lot.
