### ISSUE TITLE
Support `+++` front matter stripping

### ISSUE THREAD

**Issue by dancek** [makeworld-the-better-one/md2gemini#6]
Hi!

Great project, I was thinking I'd need to make something like this but you'd already written it! 👏

I'd love to have the front matter stripped also for `+++` (used by [Zola with TOML front matters](https://www.getzola.org/documentation/content/page/#front-matter)). It's a trivial change but I'm not sure if you'd rather have another CLI argument for it or to just treat both `---` and `+++` when called with `--jekyll`.

**Comment by makeworld-the-better-one** [comment]
Hello, happy to hear you're using it!

I was thinking to add a `--frontmatter` flag which will remove either types of front matter when enabled. I'll leave the `--jekyll` option there for compatibility, but it will only apply to `---`. Does that sound sensible?

I'll close the issue once I add this, and upload a new release to PyPi. Thanks for the suggestion!

**Comment by dancek** [comment]
That sounds great!

**Comment by makeworld-the-better-one** [comment]
v1.3.1 is now released and available on PyPI with this feature. All in a day's work :smile:
