### ISSUE TITLE
Convert md links to .gmi

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/md2gemini#7]
Inspired by [this line](https://github.com/jansc/til/blob/fb7a78381dab8c3ccea019b54922f4467048b789/generate-gemini.sh#L21) of code in someone's script:
```bash
sed -i'.bak' -e 's/\.md/\.gmi/g' index.gmi
```
It'd be nice if there was an option that would automatically do this.

**Comment by makeworld-the-better-one** [comment]
@jansc

**Comment by jansc** [comment]
That would be perfect!

**Comment by makeworld-the-better-one** [comment]
Added, it will be in the next release.
